apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"wppconnect"},"name":"wppconnect","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"wppconnect"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":0},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"wppconnect"}},"spec":{"containers":[{"image":"wppconnect-wppconnect-server:latest","imagePullPolicy":"IfNotPresent","livenessProbe":{"initialDelaySeconds":60,"periodSeconds":10,"tcpSocket":{"port":21465}},"name":"wppconnect","ports":[{"containerPort":21465}],"readinessProbe":{"initialDelaySeconds":30,"periodSeconds":5,"tcpSocket":{"port":21465}},"resources":{"limits":{"cpu":"1000m","memory":"2Gi"},"requests":{"cpu":"500m","memory":"1Gi"}}}]}}}}
  creationTimestamp: "2025-12-16T20:08:35Z"
  generation: 1
  labels:
    app: wppconnect
  name: wppconnect
  namespace: default
  resourceVersion: "196670"
  uid: 3ab3189f-bac8-49b9-a4c0-ccdcc297f309
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wppconnect
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wppconnect
    spec:
      containers:
      - image: wppconnect-wppconnect-server:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 21465
          timeoutSeconds: 1
        name: wppconnect
        ports:
        - containerPort: 21465
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 21465
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-12-16T20:08:35Z"
    lastUpdateTime: "2025-12-16T20:09:07Z"
    message: ReplicaSet "wppconnect-84459f4779" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-12-19T19:18:46Z"
    lastUpdateTime: "2025-12-19T19:18:46Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
