apiVersion: apps/v1
kind: Deployment
metadata:
  name: wppgateway
  namespace: default
  labels:
    app: wppgateway
spec:
  replicas: 1

  revisionHistoryLimit: 5

  selector:
    matchLabels:
      app: wppgateway

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

  template:
    metadata:
      labels:
        app: wppgateway
    spec:
      containers:
      - name: wppgateway
        image: wppgateway:1.0.0
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 8080
          protocol: TCP

        env:
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-dev-secret
              key: password

        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3

        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"

        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File

      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
